
server:
  port: 8091

#键值对
#food:
#  rice: 米饭
#  meat: 烤肉

#流式语法
#food: {meat: 烤肉,rice: 拌饭}

#数组语法
food:
  meat: 烤肉,辣椒炒肉,酱牛肉
  rice: 拌饭

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: 123456!@#

info:
  username: ENC(/8JKuPIQwa2zGbx3v9bObQ==)
  password: ENC(SxGXJKYdM03EDeuZIOjKuA==)

